# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
# llm:
#   api_type: "openai"  # or azure / ollama / groq etc.
#   model: "gpt-4-turbo"  # or gpt-3.5-turbo
#   base_url: "https://api.openai.com/v1"  # or forward url / other llm url
#   api_key: "YOUR_API_KEY"


llm:
  api_type: "ollama"  # or azure / ollama / open_llm etc. Check LLMType for more options
  model: "qwen2.5:7iq4m32"  # or gpt-3.5-turbo-1106 / gpt-4-1106-preview
  base_url: "http://127.0.0.1:11434/api"  # or forward url / other llm url
  # api_key: "sk-0b8d6a9c1c9e4b87b06148653bbc2505"
repair_llm_output: true